#!/bin/bash

# try to stop all existing server
nginx -s stop 2>/dev/null

# start nginx reverse proxy server
nginx -c ~/dlna-proxy/nginx.conf

# start rclone dlna server
rclone serve dlna --name DLNA --addr localhost:7879 qsc-r:DLNA

# wait for the rclone serve process to be interrupted (Ctrl+C)
wait $!

# stop the nginx server
nginx -s stop
